import blogThumb1 from '../assets/imgs/blogThumb1.png'
import blogThumb2 from '../assets/imgs/blogThumb2.jpg'
import blogThumb3 from '../assets/imgs/blogThumb3.jpg'
import blogThumb4 from '../assets/imgs/blogThumb4.jpg'
import blogThumb5 from '../assets/imgs/blogThumb5.jpg'
import blogThumb6 from '../assets/imgs/blogThumb6.jpg'
import blogThumb7 from '../assets/imgs/blogThumb7.jpg'
import blogThumb8 from '../assets/imgs/blogThumb8.jpg'
import blogThumb9 from '../assets/imgs/blogThumb9.jpg'
import blogThumb10 from '../assets/imgs/blogThumb10.jpg'
import blogThumb11 from '../assets/imgs/blogThumb11.jpg'
import blogThumb12 from '../assets/imgs/blogThumb12.jpg'
import blogThumb13 from '../assets/imgs/blogThumb13.jpg'
import blogThumb14 from '../assets/imgs/blogThumb14.jpg'
import blogThumb15 from '../assets/imgs/blogThumb15.jpg'
import blogThumb16 from '../assets/imgs/blogThumb16.jpg'
import blogThumb17 from '../assets/imgs/blogThumb17.jpg'
import blogThumb18 from '../assets/imgs/blogThumb18.jpg'
import blogThumb19 from '../assets/imgs/blogThumb19.jpg'
import blogThumb20 from '../assets/imgs/blogThumb20.jpg'
import blogThumb21 from '../assets/imgs/blogThumb21.jpg'
import blogThumb22 from '../assets/imgs/blogThumb22.jpg'
import blogThumb23 from '../assets/imgs/blogThumb23.jpg'
import blogThumb24 from '../assets/imgs/blogThumb24.jpg'
import blogThumb25 from '../assets/imgs/blogThumb25.jpg'
import blogThumb26 from '../assets/imgs/blogThumb26.jpg'
import blogThumb27 from '../assets/imgs/blogThumb27.jpg'
import blogThumb28 from '../assets/imgs/blogThumb28.jpg'
import blogThumb29 from '../assets/imgs/blogThumb29.jpg'
import blogThumb30 from '../assets/imgs/blogThumb30.jpg'
import blogThumb31 from '../assets/imgs/blogThumb31.jpg'
import blogThumb32 from '../assets/imgs/blogThumb32.jpg'
import blogThumb33 from '../assets/imgs/blogThumb33.jpg'
import blogThumb34 from '../assets/imgs/blogThumb34.jpg'
import blogThumb35 from '../assets/imgs/blogThumb35.jpg'
import blogThumb36 from '../assets/imgs/blogThumb36.jpg'
import blogThumb37 from '../assets/imgs/blogThumb37.jpg'
import blogThumb38 from '../assets/imgs/blogThumb38.jpg'
import blogThumb39 from '../assets/imgs/blogThumb39.jpg'
import blogThumb40 from '../assets/imgs/blogThumb40.jpg'
import blogThumb41 from '../assets/imgs/blogThumb41.jpg'
import blogThumb42 from '../assets/imgs/blogThumb42.jpg'
import authorAvt1 from '../assets/imgs/authorAvt1.jpeg'

import editorPickedImage1 from '../assets/imgs/editorPickedImage1.jpg'
import editorPickedImage2 from '../assets/imgs/editorPickedImage2.jpg'
import editorPickedImage3 from '../assets/imgs/editorPickedImage3.jpg'
import editorPickedImage4 from '../assets/imgs/editorPickedImage4.jpg'
import editorPickedImage5 from '../assets/imgs/editorPickedImage5.jpg'
import editorPickedImage6 from '../assets/imgs/editorPickedImage6.jpg'
import editorPickedImage7 from '../assets/imgs/editorPickedImage7.jpg'
import editorPickedImage8 from '../assets/imgs/editorPickedImage8.jpg'

import highlightThumb1 from '../assets/imgs/highlightThumb1.jpg'
import highlightThumb2 from '../assets/imgs/highlightThumb2.jpg'
import highlightThumb3 from '../assets/imgs/highlightThumb3.jpg'
import highlightThumb4 from '../assets/imgs/highlightThumb4.jpg'
import highlightThumb5 from '../assets/imgs/highlightThumb5.jpg'
import highlightThumb6 from '../assets/imgs/highlightThumb6.jpg'
import highlightThumb7 from '../assets/imgs/highlightThumb7.jpg'
import highlightThumb8 from '../assets/imgs/highlightThumb8.jpg'

import blogThumb43 from '../assets/imgs/blogThumb43.jpg'
import categoryThumb7 from '../assets/imgs/categoryThumb7.jpg'
import blogThumb44 from '../assets/imgs/blogThumb44.jpg'
import blogThumb45 from '../assets/imgs/blogThumb45.jpg'
import blogThumb46 from '../assets/imgs/blogThumb46.jpg'
import categoryThumb3 from '../assets/imgs/categoryThumb3.jpg'
import blogThumb47 from '../assets/imgs/blogThumb47.jpg'
import blogThumb48 from '../assets/imgs/blogThumb48.jpg'
import blogThumb49 from '../assets/imgs/blogThumb49.jpg'
import blogThumb50 from '../assets/imgs/blogThumb50.jpg'
import blogThumb51 from '../assets/imgs/blogThumb51.jpg'
import blogThumb52 from '../assets/imgs/blogThumb52.jpg'
import blogThumb53 from '../assets/imgs/blogThumb53.jpg'
import blogThumb54 from '../assets/imgs/blogThumb54.jpg'
import blogThumb55 from '../assets/imgs/blogThumb55.jpg'
import blogThumb56 from '../assets/imgs/blogThumb56.jpg'

// editorPickedImage3
// blogThumb43
// blogThumb5
// editorPickedImage4
// blogThumb19
// categoryThumb7
// blogThumb44
// blogThumb45
// blogThumb30
// blogThumb46
// categoryThumb3
// blogThumb22
// blogThumb47
// blogThumb48
// blogThumb49
// editorPickedImage6
// blogThumb50
// blogThumb51
// blogThumb14
// blogThumb52
// blogThumb53
// blogThumb54
// blogThumb55
// blogThumb7
// blogThumb56
// blogThumb10

const initState = {
   blogs: [
      {
         id: 1,
         image: blogThumb1,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Blog Post Medium',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 2,
         image: blogThumb2,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Blog Post Small',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 3,
         image: blogThumb3,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         likes: 0,
         type: 1,
      },
      {
         id: 4,
         image: blogThumb4,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Simple Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 5,
         image: blogThumb5,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 6,
         image: blogThumb6,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 7,
         image: blogThumb7,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 2,
         styles: {},
         type: 1,
      },
      {
         id: 8,
         image: blogThumb8,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 2,
         styles: {},
         type: 1,
      },

      {
         id: 9,
         image: blogThumb9,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Double Item Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 10,
         image: blogThumb10,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 11,
         image: blogThumb11,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 12,
         image: blogThumb12,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 13,
         image: blogThumb13,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 14,
         image: blogThumb14,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 15,
         image: blogThumb15,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 16,
         image: blogThumb16,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 17,
         image: blogThumb17,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 18,
         image: blogThumb18,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },
      {
         id: 19,
         image: blogThumb19,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 4,
      },

      {
         id: 20,
         image: blogThumb20,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'You don’t have to be rich to travel well',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam…',
         date: 'November 30, 2020',
         createAt: 1686735683888,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },

      {
         id: 21,
         image: blogThumb21,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Travel is never a matter of money but of courage',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam…',
         date: 'November 30, 2020',
         createAt: 1686735683123,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 22,
         image: blogThumb22,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Then I realized adventures are the best way to learn',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam…',
         date: 'November 30, 2020',
         createAt: 1686735683777,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 23,
         image: blogThumb23,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam…',
         date: 'October 26, 2020',
         createAt: 1686735682890,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 24,
         image: blogThumb24,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam…',
         date: 'October 11, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },

      {
         id: 25,
         image: editorPickedImage6,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Simple Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua. Ut enim ad mini veniam, quis nostrud',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 26,
         image: editorPickedImage7,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Simple Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua. Ut enim ad mini veniam, quis nostrud',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 27,
         image: editorPickedImage8,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Simple Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua. Ut enim ad mini veniam, quis nostrud',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 28,
         image: editorPickedImage1,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Nathan Matthews',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 29,
         image: editorPickedImage2,
         author: 'Julianna Galanis',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 30,
         image: editorPickedImage3,
         author: 'Mel Granville',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 31,
         image: editorPickedImage4,
         author: 'Cassandra Lynn',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 32,
         image: editorPickedImage5,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: '20 Nov',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 33,
         image: blogThumb25,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 25, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 34,
         image: blogThumb26,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 24, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 35,
         image: blogThumb27,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 24, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 36,
         image: blogThumb28,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 20, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 37,
         image: blogThumb29,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 20, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 38,
         image: blogThumb30,
         author: 'Small Blog Post',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'October 19, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },

      {
         id: 99,
         image: null,
         author: 'Scott Jackson',
         avatar: null,
         title: ['Life if a Journey.', 'Make', 'the Best of it.'],
         desc: '',
         createAt: 1686735683881,
         date: 'July 3, 2023',
         styles: {},
         type: 3,
         comments: 0,
         likes: 0,
      },
      {
         id: 98,
         image: null,
         author: 'Lao Tzu, Chinese philosopher',
         avatar: null,
         title: ['A journey is Best Measured.', 'in Friend,', 'Rather Than Miles'],
         desc: '',
         createAt: 1686735683881,
         date: 'July 3, 2023',
         styles: {},
         type: 3,
         comments: 0,
         likes: 0,
      },

      {
         id: 39,
         image: highlightThumb1,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 40,
         image: highlightThumb2,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 41,
         image: highlightThumb3,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 42,
         image: highlightThumb4,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 43,
         image: highlightThumb5,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 44,
         image: highlightThumb6,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 45,
         image: highlightThumb7,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 46,
         image: highlightThumb8,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip et dolore magna',
         date: 'July 3, 2021',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },

      {
         id: 47,
         image: blogThumb25,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 48,
         image: blogThumb27,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 49,
         image: blogThumb31,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 50,
         image: blogThumb32,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 51,
         image: blogThumb35,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 52,
         image: blogThumb33,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 53,
         image: blogThumb34,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 54,
         image: null,
         author: 'Paulo Coelho, Brazilian writer',
         avatar: null,
         title: ['If you think adventure is dangerous', 'try routine,', "it's lethal"],
         desc: '',
         createAt: 1686735683881,
         date: 'July 3, 2023',
         styles: {},
         comments: 0,
         likes: 0,
         type: 3,
      },
      {
         id: 55,
         image: blogThumb39,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 56,
         image: blogThumb37,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 57,
         image: blogThumb38,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 58,
         image: blogThumb36,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 59,
         image: blogThumb40,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 60,
         image: blogThumb42,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },
      {
         id: 61,
         image: blogThumb41,
         author: 'Herman Ledford',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor',
         date: 'November 18, 2020',
         createAt: 1686735683583,
         comments: 2,
         likes: 0,
         styles: {},
         type: 2,
      },

      // blog feed 2
      {
         id: 62,
         image: editorPickedImage3,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 63,
         image: blogThumb43,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 64,
         image: blogThumb5,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 65,
         image: editorPickedImage4,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 66,
         image: blogThumb19,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 67,
         image: categoryThumb7,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 68,
         image: blogThumb44,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 69,
         image: blogThumb45,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 70,
         image: blogThumb30,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 71,
         image: blogThumb46,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 72,
         image: categoryThumb3,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 73,
         image: blogThumb22,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 74,
         image: blogThumb47,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 75,
         image: blogThumb48,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 76,
         image: blogThumb49,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 77,
         image: editorPickedImage6,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 78,
         image: blogThumb50,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 79,
         image: blogThumb51,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 80,
         image: blogThumb14,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 81,
         image: blogThumb52,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 82,
         image: blogThumb53,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 83,
         image: blogThumb54,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 84,
         image: blogThumb55,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 85,
         image: blogThumb7,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 86,
         image: blogThumb56,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
      {
         id: 87,
         image: blogThumb10,
         author: 'Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim ad minim veniam, quis ut aliquip exea',
         date: 'November 23, 2020',
         createAt: 1686735683881,
         comments: 2,
         likes: 0,
         styles: {},
         type: 1,
      },
   ],

   blogFeed: [
      { blogId: 1, type: 1, styles: {} },
      { blogId: 2, type: 1, styles: { small: true, noOverlayContent: true } },
      { blogId: 3, type: 1, styles: { small: true, visual: true } },
      { blogId: 4, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 5, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 99, type: 3 },
      { blogId: 6, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 7, type: 2 },
      { blogId: 8, type: 2 },
   ],

   blogFeed2: [
      { blogId: 62, type: 1, styles: { square: true, visual: true } },
      { blogId: 63, type: 1, styles: { square: true, visual: true } },
      { blogId: 64, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 65, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 66, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 67, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 68, type: 1, styles: { square: true, visual: true } },
      { blogId: 69, type: 1, styles: { square: true, visual: true } },
      { blogId: 70, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 71, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 72, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 73, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 74, type: 1, styles: { square: true, visual: true } },
      { blogId: 75, type: 1, styles: { square: true, visual: true } },
      { blogId: 76, type: 1, styles: { square: true, visual: true } },
      { blogId: 77, type: 1, styles: { square: true, visual: true } },
      { blogId: 78, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 79, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 80, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 81, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 82, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 83, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 84, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 85, type: 1, styles: { square: true, visual: true, squareSmall: true } },
      { blogId: 86, type: 1, styles: { square: true, visual: true } },
      { blogId: 87, type: 1, styles: { square: true, visual: true } },
   ],

   blogGallery: [9, 10, 11, 12, 13, 98, 14, 15, 16, 17, 18, 19],

   recentPosts: [20, 21, 22, 23, 24],

   editorPinkedNews: [25, 26, 27, 28, 29, 30, 31, 32],

   moreStories: [25, 26, 27, 4, 5, 19, 6, 12, 33, 34, 13, 35, 36, 37, 38],

   blogHighlights: [39, 40, 41, 42, 43, 44, 45, 46],

   moreBlogsByAuthor: [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
}

function blogReducer(state = initState, action) {
   switch (action.type) {
      case '':
         return state

      default:
         return state
   }
}

export default blogReducer
