import blogThumb1 from '../assets/imgs/blogThumb1.png'
import blogThumb2 from '../assets/imgs/blogThumb2.jpg'
import blogThumb3 from '../assets/imgs/blogThumb3.jpg'
import blogThumb4 from '../assets/imgs/blogThumb4.jpg'
import blogThumb5 from '../assets/imgs/blogThumb5.jpg'
import blogThumb6 from '../assets/imgs/blogThumb6.jpg'
import blogThumb7 from '../assets/imgs/blogThumb7.jpg'
import blogThumb8 from '../assets/imgs/blogThumb8.jpg'
import blogThumb9 from '../assets/imgs/blogThumb9.jpg'
import blogThumb10 from '../assets/imgs/blogThumb10.jpg'
import blogThumb11 from '../assets/imgs/blogThumb11.jpg'
import blogThumb12 from '../assets/imgs/blogThumb12.jpg'
import blogThumb13 from '../assets/imgs/blogThumb13.jpg'
import blogThumb14 from '../assets/imgs/blogThumb14.jpg'
import blogThumb15 from '../assets/imgs/blogThumb15.jpg'
import blogThumb16 from '../assets/imgs/blogThumb16.jpg'
import blogThumb17 from '../assets/imgs/blogThumb17.jpg'
import blogThumb18 from '../assets/imgs/blogThumb18.jpg'
import blogThumb19 from '../assets/imgs/blogThumb19.jpg'
import authorAvt1 from '../assets/imgs/authorAvt1.jpeg'

const initState = {
   blogs: [
      {
         id: 1,
         image: blogThumb1,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Blog Post Medium',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 2,
         image: blogThumb2,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Blog Post Small',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 3,
         image: blogThumb3,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 4,
         image: blogThumb4,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Simple Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 5,
         image: blogThumb5,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Blog Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 6,
         image: blogThumb6,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Super Simple Post',
         desc: '«Travel is the healthiest addiction»',
         date: 'July 2, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 1,
      },
      {
         id: 7,
         image: blogThumb7,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 2,
         styles: {},
         type: 1,
      },
      {
         id: 8,
         image: blogThumb8,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Lorem ipsum dolor sit amet',
         desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         likes: 2,
         styles: {},
         type: 1,
      },

      {
         id: 9,
         image: blogThumb9,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Double Item Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 10,
         image: blogThumb10,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 11,
         image: blogThumb11,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 12,
         image: blogThumb12,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 13,
         image: blogThumb13,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 14,
         image: blogThumb14,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 15,
         image: blogThumb15,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 16,
         image: blogThumb16,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 17,
         image: blogThumb17,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 18,
         image: blogThumb18,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },
      {
         id: 19,
         image: blogThumb19,
         author: 'By Scott Jackson',
         avatar: authorAvt1,
         title: 'Medium Blog Post',
         desc: 'Lorem ipsum dolor sit ametcon sectetur adipisicing elit, sed doiusmod tempor incidi labore et dolore. agna aliqua lorem ipsum. Dolore magnam aliquam quaerat voluptatem. Nemo enim ipsam voluptatem quia voluptas.',
         date: 'July 3, 2023',
         createAt: 1686735683881,
         comments: 2,
         styles: {},
         type: 4,
      },

      {
         id: 99,
         image: null,
         author: 'By Scott Jackson',
         avatar: null,
         title: ['Life if a Journey.', 'Make', 'the Best of it.'],
         desc: '',
         createAt: 1686735683881,
         date: 'July 3, 2023',
         styles: {},
         type: 3,
         comments: 0,
         likes: 0,
      },
      {
         id: 98,
         image: null,
         author: 'Lao Tzu, Chinese philosopher',
         avatar: null,
         title: ['A journey is Best Measured.', 'in Friend,', 'Rather Than Miles'],
         desc: '',
         createAt: 1686735683881,
         date: 'July 3, 2023',
         styles: {},
         type: 3,
         comments: 0,
         likes: 0,
      },
   ],

   blogFeed: [
      { blogId: 1, type: 1, styles: {} },
      { blogId: 2, type: 1, styles: { small: true, noOverlayContent: true } },
      { blogId: 3, type: 1, styles: { small: true, visual: true } },
      { blogId: 4, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 5, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 99, type: 3 },
      { blogId: 6, type: 1, styles: { extraSmall: true, visual: true } },
      { blogId: 7, type: 2 },
      { blogId: 8, type: 2 },
   ],

   blogGallery: [9, 10, 11, 12, 13, 98, 14, 15, 16, 17, 18, 19],
}

function blogReducer(state = initState, action) {
   switch (action.type) {
      case '':
         return state

      default:
         return state
   }
}

export default blogReducer
